resolver 127.0.0.11 valid=10s;

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/assets/ {
        rewrite ^/api/assets/(.*)$ /$1 break;
        set $upstream_assets http://asset-service:8001;
        proxy_pass $upstream_assets;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/loans/ {
        rewrite ^/api/loans/(.*)$ /$1 break;
        set $upstream_loans http://loan-service:8002;
        proxy_pass $upstream_loans;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}